core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
]

infinitescroll/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("core.urls", "core"), namespace="core")),
]

core/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.FloatField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)

core/views.py
from django.views.generic import ListView
from core.models import Product

class HomeView(ListView):
    model = Product
    template_name = "core/index.html"
    context_object_name = "products"
    paginate_by = 10
    ordering = "pk"

    def get_template_names(self, *args, **kwargs):
        if self.request.htmx:
            return "core/product-list.html"
        else:
            return self.template_name

core/templates/core/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Infinite Scroll with Django+htmx</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="{% static 'js/htmx.min.js' %}" defer></script>

  </head>
  <body>
    <div>
          {% include 'core/product-list.html' with products=products %}
    </div>
  </body>
</body>
</html>

core/templates/core/product-list.html
{% for product in products %}
  {% if forloop.last %}
    <div 
        hx-trigger="revealed"
        hx-swap="afterend"
        hx-get="{% url 'core:home' %}?page={{ page_obj.number|add:1 }}"
    >
  {% else %}
    <div>
  {% endif %}
      <h2>{{ product.name }}</h2>
      <p>{{ product.description }}</p>
      <p>{{ product.price }}</p>
    </div>
{% endfor %}